---
- name: Configure Docker and Deploy Insurance App
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull the Docker image
      docker_image:
        name: shubhamgunjal1619/insure-me
        tag: "3.0"
        source: pull

    - name: Remove existing container if any
      docker_container:
        name: insure-me
        state: absent
        force_kill: yes   

    - name: Run Insurance App container
      docker_container:
        name: insure-me
        image: shubhamgunjal1619/insure-me:3.0
        state: started
        restart_policy: always
        recreate: yes
        force_kill: yes
        published_ports:
          - "8084:8080"
